# This is a basic workflow to help you get started with Actions

name: Flutter web build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches:
      - master


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Web build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter config --enable-web
      - run: flutter pub get
      #    - run: flutter test
      - run: flutter build web --release
      - run: |
          cd build/web
          git config --global init.defaultBranch master
          git init
          # type configurations: your user.email and user.name followed lines
          git config --global user.email jameschoi97@nyu.edu
          git config --global user.name jameschoi97
          git status
          # change this remote url for examle your remote url is https://github.com/onatcipli/flutter_web.git then the following:
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout -b gh-pages
          git add --all
          git commit -m "Automated Web Update"
          git push origin gh-pages -f
